class_name TutorialStepData
extends Resource

enum TutorialCondition {
	IS_CLAPPING,
	TTS_FINISHED,
	IS_PLAYING,
	IS_PAUSED,
	TIMER_AT_ZERO,
	TIMER_IDLE,
	KICK_RING_FULL,
	KICK_COUNT_SNAPPED_AND_PLAYING,
	STOMPED_ENOUGH,
	CLAP_RING_FULL,
	BEAT_REMOVED,
	CLAP_COUNT_SNAPPED_AND_PLAYING,
	CLAPPED_ENOUGH,
	BASS_TRACK_SELECTED,
	BASS_RECORDING_OR_TTS_DONE,
	BASS_RECORDING_ACTIVE,
	ALWAYS,
	COUNTDOWN_TICK = 17,
	NEVER = 18,
	KNOB_AT_MIX_TARGET = 19,
	KNOB_AT_OUTSIDE_TARGET = 20,
	KNOB_AT_TARGET = 21,
}

enum TutorialOutcome {
	NONE,
	NOOP,
	SHOW_INTRO,
	PLACE_KICK_BEATS,
	START_TIMER_AND_UNLOCK,
	ON_PAUSED,
	ON_KICK_RING_FILLED,
	START_SHORT_TIMER,
	BEGIN_STOMP_PHASE,
	END_STOMP_PHASE,
	SHOW_CLAP_RING,
	PLACE_CLAP_BEATS,
	START_CLAP_LISTEN_TIMER,
	STOP_PLAYBACK,
	ON_CLAP_RING_FILLED,
	ON_BEAT_REMOVED,
	START_LISTEN_AGAIN_TIMER,
	BEGIN_CLAP_COUNT,
	END_CLAP_PHASE,
	SHOW_BASS_LAYER,
	SETUP_BASS_RECORDER,
	ON_BASS_RECORDING_STARTED,
	END_FAST_TTS_AND_WAIT,
	SHOW_CHAOS_TRIANGLE,
	SHOW_CHAOSPAD_STAR,
	ON_CHAOSPAD_STAR_REACHED,
	ON_CHAOSPAD_LISTENED,
	SHOW_MIX_STAR,
	ON_MIX_STAR_REACHED,
	SHOW_OUTSIDE_STAR,
	ON_OUTSIDE_STAR_REACHED,
	FINISH_TUTORIAL,
	## Skips the TTS countdown steps when bass recording starts early.
	SKIP_BASS_INTRO,
}

@export var instruction: String = ""
@export var condition: TutorialCondition = TutorialCondition.NEVER

@export var outcome: TutorialOutcome = TutorialOutcome.NONE
